name: release

on:
  workflow_run:
    workflows:
      - Unittests
    branches:
      - release
    types:
      - completed
jobs:
  build:
    name: release
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Create tag
        uses: actions/github-script@v9.0.0
        with:
          script: |
            const date = new Date();
            const current_date = `${date.getDate()}${String(date.getMonth() + 1).padStart(2, 0)}${date.getFullYear()}`;
            github.rest.git.createRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: `refs/tags/release-${current_date}`,
              sha: context.sha
            })
